### ISSUE TITLE
**Request** to upload other configs and dots

### ISSUE THREAD

**Issue by 0xSDX** [NeuronSooup/Gnome-topbar-le-dots#1]
### Congrats on getting a huge number of upvotes over r/unixporn
![rice](https://user-images.githubusercontent.com/66586954/213388887-df5e9e1e-b86d-455b-96fb-2322bc2e295c.png)

I would like to request further more info and if possible the config files relating to:
- Neofetch / Terminal theme (especially that particular yellow/blue text scheme)
- Firefox `custom css` based on Vinceliuice's WhiteSur modifications

**Thankyou for posting the rice. Awaiting your response.**

**Comment by NeuronSooup** [comment]
For neofetch, Im using a custom theme with dracular color scheme in zsh 
Firefox custom css is legit just changing the background color to #101010 LoL

**Comment by 0xSDX** [comment]
> For neofetch, Im using a custom theme with dracular color scheme in zsh Firefox custom css is legit just changing the background color to #101010 LoL

Would be really glad if you could share the neofetch color scheme.

**Comment by NeuronSooup** [comment]
please check my reply again, I have already told you that I'm using dracular color scheme
